### ISSUE TITLE
Blog Category,Tag,Comment not shown

### ISSUE THREAD

**Issue by KharisG1234T** [webbycrown/blog-for-bagisto#11] opened 2024-10-03 08:55 UTC
![image](https://github.com/user-attachments/assets/4303dcf1-e1c1-497e-b9ce-fe9e5645339c)
![image](https://github.com/user-attachments/assets/d1e71c38-42ad-45c8-bf55-a7c17dc9ce36)
![image](https://github.com/user-attachments/assets/ed72a672-85c2-4fa4-82ec-43650bb7eacb)

**Comment by B2rana** [comment] 2024-10-06 15:52
Hi, they are using a copy of my extension (https://bagisto.com/en/extensions/laravel-ecommerce-blog-extension/), a new version will be released next week.

**Comment by AMDarter** [comment] 2024-11-08 14:42
I have the same problem. New instance of Bagisto, with only this package installed. PHP 8.1. I've updated the route in https://github.com/webbycrown/blog-for-bagisto/issues/13


`LOG.error: Invalid column type: number { "exception": {} }`

![image](https://github.com/user-attachments/assets/5c5978ac-f48f-4cd5-a645-a245301b0739)

**Comment by adarter-tc** [comment] 2024-11-09 15:05
Change the 'number' type to 'integer' for the following files:
- \vendor\webbycrown\blog-for-bagisto\src\Datagrids\BlogDataGrid.php
- \vendor\webbycrown\blog-for-bagisto\src\Datagrids\CategoryDataGrid.php
- \vendor\webbycrown\blog-for-bagisto\src\Datagrids\CommentDataGrid.php
- \vendor\webbycrown\blog-for-bagisto\src\Datagrids\TagDataGrid.php

```php
$this->addColumn([
  'index'      => 'id',
  'label'      => trans('blog::app.datagrid.id'),
  'type'       => 'integer', // change from 'number' to 'integer'
  'searchable' => false,
  'sortable'   => true,
  'filterable' => true,
]);
```

https://github.com/webbycrown/blog-for-bagisto/blob/959dfbf455f710bcc8072c6ab210d83e30811f97/src/Datagrids/CommentDataGrid.php#L42-L65

**Comment by adarter-tc** [comment] 2024-11-09 15:09
Looks like there is already a PR for this. https://github.com/webbycrown/blog-for-bagisto/pull/12

**Comment by akashcsoni** [comment] 2024-11-11 08:06
Hello @KharisG1234T 

Thank you, the issue is resolved.

**Closed as completed by akashcsoni** 2024-11-11 08:06 UTC
